### ISSUE TITLE
Can I talk you into tagging a minimal image too?

### ISSUE THREAD

**Issue by binford2k** [wanix/dockerfile-showoff#2]
This got my image down to 80mb, and was fully functional other than building PDF files with pdfkit and live code examples using a runtime other than ruby or shell.

```
FROM gliderlabs/alpine
MAINTAINER Ben Ford <ben.ford@puppet.com>
WORKDIR /var/cache/showoff
RUN apk add --no-cache ruby ruby-dev zlib-dev build-base git \
        && gem install showoff --no-ri --no-rdoc             \
        && apk del --purge binutils-libs binutils isl libgomp libatomic mpfr3 mpc1 gcc make musl-dev libc-dev fortify-headers g++ build-base

CMD ["showoff", "serve"]
```

I was also considering building a max image with perl & python runtimes too, for running live code examples. That would add another 80 mb.

Would you consider tagging your releases with the Showoff version?

**Comment by wanix** [comment]
Hi, yes I will consider that, thanks

**Comment by binford2k** [comment]
I pushed up a minimal image at `binford2k/showoff`. I linked to yours if people want anything more than just the basic image.

**Comment by wanix** [comment]
I shrink

**Comment by wanix** [comment]
I shrink a little and it seems good.
I may try a '-minimal' branch with '-min' tags later
